include: package:lint/analysis_options.yaml

linter:
  rules:
    todo: false
    prefer_final_locals: false
    avoid_print: true
    argument_type_not_assignable: false
    prefer_constructors_over_static_methods: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    avoid_shadowing_type_parameters: true
    use_rethrow_when_possible: true

analyzer:
  strong-mode:
    implicit-casts: true
    # implicit-dynamic: false
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    avoid_print: error
    dead_code: error
    unused_import: error
    unused_local_variable: error
